### ISSUE TITLE
Sign fails with missing timestamp

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/sign#538]
This command fails:

`sign code azure-key-vault -d "scratch foo" -u https://the.site -kvi **** -kvs **** -kvt **** -kvu **** -kvc **** .\scratch.1.0.0.nupkg`

```
info: Sign.Core.Signer[0]
      Submitting 'C:\Users\cnov\dev\scratch\bin\Debug\scratch.1.0.0.nupkg' for signing.
info: Sign.Core.Signer[0]
      SignAsync called for C:\Users\cnov\dev\scratch\bin\Debug\scratch.1.0.0.nupkg. Using C:\Users\cnov\AppData\Local\Temp\frxvsoeu.eht\la2t4zkk.nupkg locally.
info: Sign.Core.IDirectoryService[0]
      Extracting container file C:\Users\cnov\AppData\Local\Temp\frxvsoeu.eht\la2t4zkk.nupkg to C:\Users\cnov\AppData\Local\Temp\2ox4xsd1.h5b.
info: Sign.Core.ISignatureProvider[0]
      Signing SignTool job with 1 files
info: Sign.Core.ISignatureProvider[0]
      Signing using C:\Users\cnov\AppData\Local\Temp\2ox4xsd1.h5b\lib\net7.0\scratch.dll
info: Sign.Core.ISignatureProvider[0]
      Sign tool completed successfully
info: Sign.Core.IDirectoryService[0]
      Rebuilding container C:\Users\cnov\AppData\Local\Temp\frxvsoeu.eht\la2t4zkk.nupkg from C:\Users\cnov\AppData\Local\Temp\2ox4xsd1.h5b.
info: Sign.Core.INuGetSignTool[0]
      Signing using C:\Users\cnov\AppData\Local\Temp\frxvsoeu.eht\la2t4zkk.nupkg
fail: Sign.Core.INuGetSignTool[0]
      Value cannot be null. (Parameter 'uriString')
      System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
         at System.Uri..ctor(String uriString)
         at NuGetKeyVaultSignTool.SignCommand.SignAsync(String packagePath, String outputPath, String timestampUrl, Uri v3ServiceIndex, IReadOnlyList`1 packageOwners, SignatureType signatureType, HashAlgorithmName signatureHashAlgorithm, HashAlgorithmName timestampHashAlgorithm, Boolean overwrite, X509Certificate2 publicCertificate, RSA rsa, CancellationToken cancellationToken) in /_/NuGetKeyVaultSignTool.Core/SignCommand.cs:line 64
         at Sign.Core.NuGetSignTool.SignAsync(FileInfo file, RSA rsaPrivateKey, X509Certificate2 certificate, SignOptions options) in /_/src/Sign.Core/Tools/NuGetSignTool.cs:line 36
info: Sign.Core.ISignatureProvider[0]
      Performing attempt #2 of 3 attempts after 5s
info: Sign.Core.INuGetSignTool[0]
      Signing using C:\Users\cnov\AppData\Local\Temp\frxvsoeu.eht\la2t4zkk.nupkg
fail: Sign.Core.INuGetSignTool[0]
      Value cannot be null. (Parameter 'uriString')
      System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
         at System.Uri..ctor(String uriString)
         at NuGetKeyVaultSignTool.SignCommand.SignAsync(String packagePath, String outputPath, String timestampUrl, Uri v3ServiceIndex, IReadOnlyList`1 packageOwners, SignatureType signatureType, HashAlgorithmName signatureHashAlgorithm, HashAlgorithmName timestampHashAlgorithm, Boolean overwrite, X509Certificate2 publicCertificate, RSA rsa, CancellationToken cancellationToken) in /_/NuGetKeyVaultSignTool.Core/SignCommand.cs:line 64
         at Sign.Core.NuGetSignTool.SignAsync(FileInfo file, RSA rsaPrivateKey, X509Certificate2 certificate, SignOptions options) in /_/src/Sign.Core/Tools/NuGetSignTool.cs:line 36
info: Sign.Core.ISignatureProvider[0]
      Performing attempt #3 of 3 attempts after 11.1803398s
info: Sign.Core.INuGetSignTool[0]
      Signing using C:\Users\cnov\AppData\Local\Temp\frxvsoeu.eht\la2t4zkk.nupkg
fail: Sign.Core.INuGetSignTool[0]
      Value cannot be null. (Parameter 'uriString')
      System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
         at System.Uri..ctor(String uriString)
         at NuGetKeyVaultSignTool.SignCommand.SignAsync(String packagePath, String outputPath, String timestampUrl, Uri v3ServiceIndex, IReadOnlyList`1 packageOwners, SignatureType signatureType, HashAlgorithmName signatureHashAlgorithm, HashAlgorithmName timestampHashAlgorithm, Boolean overwrite, X509Certificate2 publicCertificate, RSA rsa, CancellationToken cancellationToken) in /_/NuGetKeyVaultSignTool.Core/SignCommand.cs:line 64
         at Sign.Core.NuGetSignTool.SignAsync(FileInfo file, RSA rsaPrivateKey, X509Certificate2 certificate, SignOptions options) in /_/src/Sign.Core/Tools/NuGetSignTool.cs:line 36
fail: Sign.Core.ISignatureProvider[0]
      Failed to sign. Attempts exceeded
info: Sign.Core.Signer[0]
      Successfully signed 'C:\Users\cnov\dev\scratch\bin\Debug\scratch.1.0.0.nupkg' in 17528 ms
```

**Comment by dtivel** [comment]
@clairernovotny, see https://github.com/novotnyllc/NuGetKeyVaultSignTool/issues/122.

**Comment by clairernovotny** [comment]
This is by design and won't be fixed... we also require a timestamp. We should fix this with argument validation and defaulting.

**Comment by dtivel** [comment]
Defaulting is out-of-scope now because of https://github.com/dotnet/sign/issues/539.
