### ISSUE TITLE
Bad Request when submitting through GH Actions

### ISSUE THREAD

**Issue by isaacrlevin** [dotnet/sign#576]
**Describe the bug**
When I follow the sample Action, I get this error in the logs

> fail: Sign.Core.Signer[0]
      Service request failed.
      Status: 400 (Bad Request)

**Repro steps**

Sample sign call

```yaml
    - name: Sign artifacts
      shell: pwsh
      run: >
        ./sign code azure-key-vault
        **/*.appxbundle
        --timestamp-url "http://timestamp.digicert.com"
        --base-directory "${{ github.workspace }}/ToSign/Nightly"
        --file-list "${{ github.workspace }}/SigningScripts/filelist.txt" 
        --publisher-name "Isaac Levin"
        --description "PresenceLight"
        --description-url "https://github.com/isaacrlevin/presencelight"
        --azure-key-vault-managed-identity true
        --azure-key-vault-url "${{ secrets.KEY_VAULT_URL }}"
        --azure-key-vault-certificate "${{ secrets.KEY_VAULT_CERTIFICATE_ID }}"
````

**Expected behavior**
Sign function completes

**Actual behavior**
Get below error

````
 fail: Sign.Core.Signer[0]
      Service request failed.
      Status: 400 (Bad Request)
      
      Content:
      <!DOCTYPE html>
      <html>
          <head>
              <title>Runtime Error</title>
              <meta name="viewport" content="width=device-width" />
              <style>
               body ***font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;*** 
               p ***font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px***
               b ***font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px***
               H1 *** font-family:"Verdana";font-weight:normal;font-size:18pt;color:red ***
               H2 *** font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon ***
               pre ***font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt***
               .marker ***font-weight: bold; color: black;text-decoration: none;***
               .version ***color: gray;***
               .error ***margin-bottom: 10px;***
               .expandable *** text-decoration:underline; font-weight:bold; color:navy; cursor:hand; ***
               @media screen and (max-width: 639px) ***
                pre *** width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; ***
               ***
               @media screen and (max-width: 479px) ***
                pre *** width: 280px; ***
               ***
              </style>
          </head>
      
          <body bgcolor="white">
      
                  <span><H1>Server Error in '/' Application.<hr width=[100](https://github.com/isaacrlevin/presencelight/actions/runs/3972595485/jobs/6841724217#step:7:101)% size=1 color=silver></H1>
      
                  <h2> <i>Runtime Error</i> </h2></span>
      
                  <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">
      
                  <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
                  <br><br>
      
                  <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>
      
                  <table width=100% bgcolor="#ffffcc">
                     <tr>
                        <td>
                            <code><pre>
      
      &lt;!-- Web.Config Configuration File --&gt;
      
      &lt;configuration&gt;
          &lt;system.web&gt;
              &lt;customErrors mode=&quot;Off&quot;/&gt;
          &lt;/system.web&gt;
      &lt;/configuration&gt;</pre></code>
      
                        </td>
                     </tr>
                  </table>
      
                  <br>
      
                  <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>
      
                  <table width=100% bgcolor="#ffffcc">
                     <tr>
                        <td>
                            <code><pre>
      
      &lt;!-- Web.Config Configuration File --&gt;
      
      &lt;configuration&gt;
          &lt;system.web&gt;
              &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
          &lt;/system.web&gt;
      &lt;/configuration&gt;</pre></code>
      
                        </td>
                     </tr>
                  </table>
      
                  <br>
      
          </body>
      </html>
      
      
      Headers:
      Cache-Control: private
      X-Content-Type-Options: REDACTED
      Strict-Transport-Security: REDACTED
      Date: Mon, 23 Jan 2023 18:29:16 GMT
      Content-Type: text/html; charset=utf-8
      Content-Length: 3420
      
      Azure.RequestFailedException: Service request failed.
      
Error: Process completed with exit code 1.
````

**Additional context**

```bash
runneradmin@fv-az365-709 MINGW64 /d/a/presencelight/presencelight
# ./sign.exe --version
0.9.0-beta.23063.3+7b32935c42c720d96ceee799980a7f5ec2d2c296

runneradmin@fv-az365-709 MINGW64 /d/a/presencelight/presencelight
# dotnet --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20348
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  3.1.120 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.113 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.308 [C:\Program Files\dotnet\sdk]
  6.0.405 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  DOTNET_ROOT       [C:\Program Files\dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
````

**Comment by clairernovotny** [comment]
Can you please increase the logging verbosity to see if there's additional information that could help?

**Comment by isaacrlevin** [comment]
increase verbosity in the sign tool or GH actions?

**Comment by dtivel** [comment]
Hi, @isaacrlevin.  I've had difficulty reproducing this.  @clairernovotny will be reaching out with a logging fix to see if that helps reveal important detail.

Searching for similar errors with Azure Key Vault, I read an issue where in incorrect Azure Key Vault URL produced a similar result (HTTP 400).  Can you confirm that the URL you're passing to the `--azure-key-vault-url` option is the same value shown in your Azure Key Vault's Overview page under "Vault URI"?

Also, does the same signing operation, when run outside of a GitHub action (e.g.:  locally), fail similarly?

**Comment by isaacrlevin** [comment]
Yes it is. What should the value of `--azure-key-vault-certificate` be? Can you provide a screenshot?

**Comment by dtivel** [comment]
Thanks for confirming.  The value of `--azure-key-vault-certificate` should be the friendly name you assigned in Azure Key Vault's Certificates page.  Here is my page:

![image](https://user-images.githubusercontent.com/12734758/216481935-7a7e4dd6-ed30-4760-a686-8e21aa1653ff.png)

I pass `--azure-key-vault-certificate MyCertificate`.

**Comment by dtivel** [comment]
If the certificate you indicate doesn't exist --- say, you typo-ed the name ---, you get a clear error indicating that's the case:
```
fail: Sign.Core.Signer[0]
      A certificate with (name/id) MyCertificate2 was not found in this key vault. If you recently deleted this certificate you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182
      Status: 404 (Not Found)
      ErrorCode: CertificateNotFound
```

Your original error was 400 (Bad request) which tells me you're already referencing a certificate that exists and that yours is a different problem.

**Comment by isaacrlevin** [comment]
I was able to get by this using another KeyVault. Now I get this error

````
./sign code azure-key-vault **/*.appxbundle --timestamp-url "http://timestamp.digicert.com/" --base-directory "/home/runner/work/presencelight/presencelight/ToSign/Nightly" --file-list "/home/runner/work/presencelight/presencelight/SigningScripts/filelist.txt"  --publisher-name "Isaac Levin" --description "***" --description-url "https://github.com/isaacrlevin/presencelight" --azure-key-vault-managed-identity true --azure-key-vault-url "***" --azure-key-vault-certificate "***" --verbosity Trace
  shell: /usr/bin/pwsh -command ". '***0***'"
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    DOTNET_ROOT: /usr/share/dotnet
##[debug]/usr/bin/pwsh -command ". '/home/runner/work/_temp/d4c62d0c-b0d6-43f5-8ce0-816[55](https://github.com/isaacrlevin/presencelight/actions/runs/4088466927/jobs/7050298875#step:8:56)6de7e0a.ps1'"
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at Sign.Cli.Kernel32.SetDllDirectoryW(String lpPathName)
   at Sign.Cli.Program.Main(String[] args) in /_/src/Sign.CLI/Program.cs:line 35
   at Sign.Cli.Program.<Main>(String[] args)
Error: Process completed with exit code 1.
````

**Comment by dtivel** [comment]
Sign CLI is only supported on Windows x64 at this time.  (Authenticode is a Windows technology, and we don't have Authenticode signing on non-Windows platforms.)

Can you retry on Windows x64?

**Comment by isaacrlevin** [comment]
Here is the work flow in question. It is using ubuntu-latest

https://github.com/isaacrlevin/presencelight/blob/main/.github/workflows/Desktop_Build.yml

**Comment by isaacrlevin** [comment]
That fixed the issue. Closing issue

**Comment by dtivel** [comment]
@isaacrlevin, I'm glad the tool is working for you now!

What was the original problem?  It seems that switching from one Azure Key Vault to another fixed the issue.  Was there some configuration on the first Key Vault that resulted in the HTTP 400 (Bad request)?

**Comment by isaacrlevin** [comment]
No it was the exact same, maybe my access policy wasn't 100% right
