### ISSUE TITLE
The client 'xxx' with object id 'xxx does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read'

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/sign#61]
The service was running fine, but all the sudden, this exception happened, with the web app service failing to start:

```
System.AggregateException: One or more errors occurred. (The client xxx' with object id 'xxx' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/xxx/resourcegroups/SignService'.) ---> Microsoft.Rest.Azure.CloudException: The client 'xxx' with object id 'xxxx' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/xxx/resourcegroups/SignService'.
   at Microsoft.Azure.Management.ResourceManager.ResourceGroupsOperations.GetWithHttpMessagesAsync(String resourceGroupName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.ResourceGroupsOperationsExtensions.GetAsync(IResourceGroupsOperations operations, String resourceGroupName, CancellationToken cancellationToken)
   at SignService.Services.ApplicationConfiguration.InitializeAsync() in C:\s\github\SignService\src\SignService\Services\ApplicationConfiguration.cs:line 80
```

I fixed it by adding back the application's (signservice-server) access to the subscription. Not sure why/how it changed :)

This [answer helped](https://stackoverflow.com/a/52982916/26346).

**Comment by Aaronontheweb** [comment]
Ran into this issue myself when using the ARM template

**Comment by onovotny** [comment]
Odd...wonder what could have removed those permissions on the resource group?

**Comment by Aaronontheweb** [comment]
In my case, I had deleted the original resource group and recreated it using the ARM template without running the InstallUtility a second time.
