### ISSUE TITLE
Signing fails at random due to files being locked

### ISSUE THREAD

**Issue by akorchev** [dotnet/sign#799]
**Describe the bug**
I am signing a VSIX package by following the instructions from this blog post: https://www.mrlacey.com/2024/10/code-signing-vsix-package-with.html

Basically running this in a Github action:

```
  sign code certificate-store "Radzen.VisualStudio/bin/Release/Radzen.VisualStudio.vsix" -cfp ${{ secrets.SM_CODE_SIGNING_CERT_SHA256_HASH }} -csp "DigiCert Software Trust Manager KSP" -k ${{ secrets.SM_FRIENDLY_NAME }} -u "http://timestamp.digicert.com"
```

The very first time I ran this action it successfully signed the VSIX. After that i has been failing consistently with this:

```
warn: Sign.Core.IDirectoryService[0]
      An exception occurred while attempting to delete directory C:\Users\runneradmin\AppData\Local\Temp\j4msfnmh.gd3.
      System.IO.IOException: The process cannot access the file 'Humanizer.dll' because it is being used by another process.
         at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
         at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
         at System.IO.DirectoryInfo.Delete(Boolean recursive)
         at Sign.Core.DirectoryService.Delete(DirectoryInfo directory) in /_/src/Sign.Core/FileSystem/DirectoryService.cs:line 52
fail: Sign.Core.ISigner[0]
      Could not sign C:\Users\runneradmin\AppData\Local\Temp\j4msfnmh.gd3\Humanizer.dll.
      System.Exception: Could not sign C:\Users\runneradmin\AppData\Local\Temp\j4msfnmh.gd3\Humanizer.dll.
         at Sign.Core.AzureSignToolSigner.<>c__DisplayClass7_0.<<SignAsync>b__0>d.MoveNext() in /_/src/Sign.Core/DataFormatSigners/AzureSignToolSigner.cs:line 114
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Sign.Core.AzureSignToolSigner.SignAsync(IEnumerable`1 files, SignOptions options) in /_/src/Sign.Core/DataFormatSigners/AzureSignToolSigner.cs:line 108
         at Sign.Core.AggregatingSigner.SignAsync(IEnumerable`1 files, SignOptions options) in /_/src/Sign.Core/DataFormatSigners/AggregatingSigner.cs:line 204
         at Sign.Core.AggregatingSigner.SignAsync(IEnumerable`1 files, SignOptions options) in /_/src/Sign.Core/DataFormatSigners/AggregatingSigner.cs:line 92
         at Sign.Core.Signer.<>c__DisplayClass3_0.<<SignAsync>b__0>d.MoveNext() in /_/src/Sign.Core/Signer.cs:line 155
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Sign.Core.Signer.SignAsync(IReadOnlyList`1 inputFiles, String outputFile, FileInfo fileList, DirectoryInfo baseDirectory, String applicationName, String publisherName, String description, Uri descriptionUrl, Uri timestampUrl, Int32 maxConcurrency, HashAlgorithmName fileHashAlgorithm, HashAlgorithmName timestampHashAlgorithm) in /_/src/Sign.Core/Signer.cs:line 84
```

**Repro steps**

I am not sure how to provide a reproduction. Maybe it is related to the VSIX file itself as it contains a lot of .dll files. Does this tool try to sign every dll file in the VSIX?

**Expected behavior**
I expect signing to always be successful.

**Actual behavior**
Signing fails at random.

**Additional context**
- Include the output of `sign --version`.

```
0.9.1-beta.24529.1+029731ca2df9d41933a09a1cc9212595a7c7932a
```
- Include the output of `dotnet --info`.
```
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.e99c892e
 MSBuild version:   17.11.9+a69bbaaf5
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20348
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.403\
.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [maui-windows]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    8.0.82/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.82\WorkloadManifest.json
   Install Type:        FileBased
 [maccatalyst]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    18.0.8303/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\18.0.8303\WorkloadManifest.json
   Install Type:        FileBased
 [ios]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    18.0.8303/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\18.0.8303\WorkloadManifest.json
   Install Type:        FileBased
 [android]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    34.0.113/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.113\WorkloadManifest.json
   Install Type:        FileBased
 [wasm-tools]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    8.0.10/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.10\WorkloadManifest.json
   Install Type:        FileBased
 [aspire]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased
Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857
.NET SDKs installed:
  6.0.135 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  6.0.427 [C:\Program Files\dotnet\sdk]
  7.0.120 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.317 [C:\Program Files\dotnet\sdk]
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.403 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
Environment variables:
  DOTNET_ROOT       [C:\Program Files\dotnet]
global.json file:
  Not found
```

**Comment by dlemstra** [comment]
Are you running this on GitHub or on your own hosted agent?

**Comment by akorchev** [comment]
I am running it on GitHub with default (free) agent.

**Comment by akorchev** [comment]
By checking the source code I found that this is actually a warning and not an exception. The actual exception is this:

```
fail: Sign.Core.IDataFormatSigner[0]
      An internal consistency check failed.
      System.Security.Cryptography.CryptographicException: An internal consistency check failed.
         at System.Security.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize)
         at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignCallback(IntPtr pCertContext, IntPtr pvExtra, UInt32 algId, Byte[] pDigestToSign, UInt32 dwDigestToSign, CRYPTOAPI_BLOB& blob)
         at AzureSign.Core.Interop.mssign32.SignerSignEx3(SignerSignEx3Flags dwFlags, SIGNER_SUBJECT_INFO* pSubjectInfo, SIGNER_CERT* pSignerCert, SIGNER_SIGNATURE_INFO* pSignatureInfo, IntPtr pProviderInfo, SignerSignTimeStampFlags dwTimestampFlags, Byte* pszTimestampAlgorithmOid, Char* pwszHttpTimeStamp, IntPtr psRequest, Void* pSipData, IntPtr* ppSignerContext, IntPtr pCryptoPolicy, SIGN_INFO* pSignInfo, IntPtr pReserved)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignFile(ReadOnlySpan`1 path, ReadOnlySpan`1 description, ReadOnlySpan`1 descriptionUrl, Nullable`1 pageHashing, ILogger logger)
         at Sign.Core.AzureSignToolSigner.RunSignTool(AuthenticodeKeyVaultSigner signer, FileInfo file, SignOptions options) in /_/src/Sign.Core/DataFormatSigners/AzureSignToolSigner.cs:line 167
fail: Sign.Core.IDataFormatSigner[0]
      An internal consistency check failed.
      System.Security.Cryptography.CryptographicException: An internal consistency check failed.
         at System.Security.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize)
         at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignCallback(IntPtr pCertContext, IntPtr pvExtra, UInt32 algId, Byte[] pDigestToSign, UInt32 dwDigestToSign, CRYPTOAPI_BLOB& blob)
         at AzureSign.Core.Interop.mssign32.SignerSignEx3(SignerSignEx3Flags dwFlags, SIGNER_SUBJECT_INFO* pSubjectInfo, SIGNER_CERT* pSignerCert, SIGNER_SIGNATURE_INFO* pSignatureInfo, IntPtr pProviderInfo, SignerSignTimeStampFlags dwTimestampFlags, Byte* pszTimestampAlgorithmOid, Char* pwszHttpTimeStamp, IntPtr psRequest, Void* pSipData, IntPtr* ppSignerContext, IntPtr pCryptoPolicy, SIGN_INFO* pSignInfo, IntPtr pReserved)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignFile(ReadOnlySpan`1 path, ReadOnlySpan`1 description, ReadOnlySpan`1 descriptionUrl, Nullable`1 pageHashing, ILogger logger)
         at Sign.Core.AzureSignToolSigner.RunSignTool(AuthenticodeKeyVaultSigner signer, FileInfo file, SignOptions options) in /_/src/Sign.Core/DataFormatSigners/AzureSignToolSigner.cs:line 167
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error 0.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error 0.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
fail: Sign.Core.IDataFormatSigner[0]
      Failed to sign. Attempts exceeded.
fail: Sign.Core.IDataFormatSigner[0]
      Failed to sign. Attempts exceeded.
```

**Comment by akorchev** [comment]
Ran it again with `--verbosity Debug` and got this output:

```
info: Sign.Core.ISigner[0]
      Submitting D:\a\radzen-next\radzen-next\Radzen.VisualStudio\bin\Release\Radzen.VisualStudio.vsix for signing.
info: Sign.Core.ISigner[0]
      SignAsync called for D:\a\radzen-next\radzen-next\Radzen.VisualStudio\bin\Release\Radzen.VisualStudio.vsix. Using C:\Users\runneradmin\AppData\Local\Temp\kjt044rc.lo2\bqwftwrv.vsix locally.
info: Sign.Core.IContainerProvider[0]
      Extracting container C:\Users\runneradmin\AppData\Local\Temp\kjt044rc.lo2\bqwftwrv.vsix to C:\Users\runneradmin\AppData\Local\Temp\fal30z3s.tk4.
info: Sign.Core.IDataFormatSigner[0]
      Signing SignTool job with 457 files.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\fal30z3s.tk4\Microsoft.AspNet.Scaffolding.12.0.dll.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\fal30z3s.tk4\Humanizer.dll.
fail: Sign.Core.IDataFormatSigner[0]
      An internal consistency check failed.
      System.Security.Cryptography.CryptographicException: An internal consistency check failed.
         at System.Security.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize)
         at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignCallback(IntPtr pCertContext, IntPtr pvExtra, UInt32 algId, Byte[] pDigestToSign, UInt32 dwDigestToSign, CRYPTOAPI_BLOB& blob)
         at AzureSign.Core.Interop.mssign32.SignerSignEx3(SignerSignEx3Flags dwFlags, SIGNER_SUBJECT_INFO* pSubjectInfo, SIGNER_CERT* pSignerCert, SIGNER_SIGNATURE_INFO* pSignatureInfo, IntPtr pProviderInfo, SignerSignTimeStampFlags dwTimestampFlags, Byte* pszTimestampAlgorithmOid, Char* pwszHttpTimeStamp, IntPtr psRequest, Void* pSipData, IntPtr* ppSignerContext, IntPtr pCryptoPolicy, SIGN_INFO* pSignInfo, IntPtr pReserved)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignFile(ReadOnlySpan`1 path, ReadOnlySpan`1 description, ReadOnlySpan`1 descriptionUrl, Nullable`1 pageHashing, ILogger logger)
         at Sign.Core.AzureSignToolSigner.RunSignTool(AuthenticodeKeyVaultSigner signer, FileInfo file, SignOptions options) in /_/src/Sign.Core/DataFormatSigners/AzureSignToolSigner.cs:line 167
fail: Sign.Core.IDataFormatSigner[0]
      An internal consistency check failed.
      System.Security.Cryptography.CryptographicException: An internal consistency check failed.
         at System.Security.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize)
         at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignCallback(IntPtr pCertContext, IntPtr pvExtra, UInt32 algId, Byte[] pDigestToSign, UInt32 dwDigestToSign, CRYPTOAPI_BLOB& blob)
         at AzureSign.Core.Interop.mssign32.SignerSignEx3(SignerSignEx3Flags dwFlags, SIGNER_SUBJECT_INFO* pSubjectInfo, SIGNER_CERT* pSignerCert, SIGNER_SIGNATURE_INFO* pSignatureInfo, IntPtr pProviderInfo, SignerSignTimeStampFlags dwTimestampFlags, Byte* pszTimestampAlgorithmOid, Char* pwszHttpTimeStamp, IntPtr psRequest, Void* pSipData, IntPtr* ppSignerContext, IntPtr pCryptoPolicy, SIGN_INFO* pSignInfo, IntPtr pReserved)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignFile(ReadOnlySpan`1 path, ReadOnlySpan`1 description, ReadOnlySpan`1 descriptionUrl, Nullable`1 pageHashing, ILogger logger)
         at Sign.Core.AzureSignToolSigner.RunSignTool(AuthenticodeKeyVaultSigner signer, FileInfo file, SignOptions options) in /_/src/Sign.Core/DataFormatSigners/AzureSignToolSigner.cs:line 167
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error 0.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error 0.
info: Sign.Core.IDataFormatSigner[0]
      Performing attempt #2 of 3 attempts after 5 s.
info: Sign.Core.IDataFormatSigner[0]
      Performing attempt #2 of 3 attempts after 5 s.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\fal30z3s.tk4\Microsoft.AspNet.Scaffolding.12.0.dll.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\fal30z3s.tk4\Humanizer.dll.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
info: Sign.Core.IDataFormatSigner[0]
      Performing attempt #3 of 3 attempts after 11.1803398 s.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
info: Sign.Core.IDataFormatSigner[0]
      Performing attempt #3 of 3 attempts after 11.1803398 s.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\fal30z3s.tk4\Microsoft.AspNet.Scaffolding.12.0.dll.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\fal30z3s.tk4\Humanizer.dll.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
fail: Sign.Core.IDataFormatSigner[0]
      Failed to sign. Attempts exceeded.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
fail: Sign.Core.IDataFormatSigner[0]
      Failed to sign. Attempts exceeded.
```

Signing seems to fail for certain files (it is always those files though).

**Comment by akorchev** [comment]
Used the `--file-list` option to reduce the number of files to sign to three. I get the same exception. Do I need to install vc_redist.x64.exe via the github action? Tried that via:

```
      - name: Download VC++ redist
        run: |
            Invoke-WebRequest https://aka.ms/vs/17/release/vc_redist.x64.exe -OutFile vc_redist.x64.exe

      - name: Install VC++ redist
        run: .\vc_redist.x64.exe /S /v/qn
```

Didn't help. Here is the latest stacktrace:

```
info: Sign.Core.ISigner[0]
      Submitting D:\a\radzen-next\radzen-next\Radzen.VisualStudio\bin\Release\Radzen.VisualStudio.vsix for signing.
info: Sign.Core.ISigner[0]
      SignAsync called for D:\a\radzen-next\radzen-next\Radzen.VisualStudio\bin\Release\Radzen.VisualStudio.vsix. Using C:\Users\runneradmin\AppData\Local\Temp\rhnafs3m.b0c\payhorfu.vsix locally.
info: Sign.Core.IContainerProvider[0]
      Extracting container C:\Users\runneradmin\AppData\Local\Temp\rhnafs3m.b0c\payhorfu.vsix to C:\Users\runneradmin\AppData\Local\Temp\vvoavmxr.s00.
info: Sign.Core.IDataFormatSigner[0]
      Signing SignTool job with 6 files.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\vvoavmxr.s00\Radzen.VisualStudio.dll.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\vvoavmxr.s00\Radzen.VisualStudio.Xaml.dll.
fail: Sign.Core.IDataFormatSigner[0]
      An internal consistency check failed.
      System.Security.Cryptography.CryptographicException: An internal consistency check failed.
         at System.Security.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize)
         at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignCallback(IntPtr pCertContext, IntPtr pvExtra, UInt32 algId, Byte[] pDigestToSign, UInt32 dwDigestToSign, CRYPTOAPI_BLOB& blob)
         at AzureSign.Core.Interop.mssign32.SignerSignEx3(SignerSignEx3Flags dwFlags, SIGNER_SUBJECT_INFO* pSubjectInfo, SIGNER_CERT* pSignerCert, SIGNER_SIGNATURE_INFO* pSignatureInfo, IntPtr pProviderInfo, SignerSignTimeStampFlags dwTimestampFlags, Byte* pszTimestampAlgorithmOid, Char* pwszHttpTimeStamp, IntPtr psRequest, Void* pSipData, IntPtr* ppSignerContext, IntPtr pCryptoPolicy, SIGN_INFO* pSignInfo, IntPtr pReserved)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignFile(ReadOnlySpan`1 path, ReadOnlySpan`1 description, ReadOnlySpan`1 descriptionUrl, Nullable`1 pageHashing, ILogger logger)
         at Sign.Core.AzureSignToolSigner.RunSignTool(AuthenticodeKeyVaultSigner signer, FileInfo file, SignOptions options) in /_/src/Sign.Core/DataFormatSigners/AzureSignToolSigner.cs:line 167
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error 0.
fail: Sign.Core.IDataFormatSigner[0]
      An internal consistency check failed.
      System.Security.Cryptography.CryptographicException: An internal consistency check failed.
         at System.Security.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize)
         at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignCallback(IntPtr pCertContext, IntPtr pvExtra, UInt32 algId, Byte[] pDigestToSign, UInt32 dwDigestToSign, CRYPTOAPI_BLOB& blob)
         at AzureSign.Core.Interop.mssign32.SignerSignEx3(SignerSignEx3Flags dwFlags, SIGNER_SUBJECT_INFO* pSubjectInfo, SIGNER_CERT* pSignerCert, SIGNER_SIGNATURE_INFO* pSignatureInfo, IntPtr pProviderInfo, SignerSignTimeStampFlags dwTimestampFlags, Byte* pszTimestampAlgorithmOid, Char* pwszHttpTimeStamp, IntPtr psRequest, Void* pSipData, IntPtr* ppSignerContext, IntPtr pCryptoPolicy, SIGN_INFO* pSignInfo, IntPtr pReserved)
         at AzureSign.Core.AuthenticodeKeyVaultSigner.SignFile(ReadOnlySpan`1 path, ReadOnlySpan`1 description, ReadOnlySpan`1 descriptionUrl, Nullable`1 pageHashing, ILogger logger)
         at Sign.Core.AzureSignToolSigner.RunSignTool(AuthenticodeKeyVaultSigner signer, FileInfo file, SignOptions options) in /_/src/Sign.Core/DataFormatSigners/AzureSignToolSigner.cs:line 167
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error 0.
info: Sign.Core.IDataFormatSigner[0]
      Performing attempt #2 of 3 attempts after 5 s.
info: Sign.Core.IDataFormatSigner[0]
      Performing attempt #2 of 3 attempts after 5 s.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\vvoavmxr.s00\Radzen.VisualStudio.Xaml.dll.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\vvoavmxr.s00\Radzen.VisualStudio.dll.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
info: Sign.Core.IDataFormatSigner[0]
      Performing attempt #3 of 3 attempts after 11.1803398 s.
info: Sign.Core.IDataFormatSigner[0]
      Performing attempt #3 of 3 attempts after 11.1803398 s.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\vvoavmxr.s00\Radzen.VisualStudio.dll.
info: Sign.Core.IDataFormatSigner[0]
      Signing C:\Users\runneradmin\AppData\Local\Temp\vvoavmxr.s00\Radzen.VisualStudio.Xaml.dll.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
fail: Sign.Core.IDataFormatSigner[0]
      Failed to sign. Attempts exceeded.
fail: Sign.Core.IDataFormatSigner[0]
      Signing failed with error -2147024864.
fail: Sign.Core.IDataFormatSigner[0]
      Failed to sign. Attempts exceeded.
```

**Comment by akorchev** [comment]
Turned out the problem was my certificate provider (DigiCert). The first successful sign used up all my tokens 😄 This motivated me to migrate to another provider and signing works again.
